### PR TITLE
widget updates

### PR DESCRIPTION
**Pull request by teharrison**

### CODE REVIEW

**Comment by briehl** [comment]
I'm a little confused about the update to proxy_mgr.lua - this adds a maximum number of containers, right? So, if user #101 tries to log in, do they just get booted with an error? At the very least, shouldn't we expand that to some really high number?

**Comment by teharrison** [comment]
My bad, the default should be insanely high for now (which would duplicate
the current state of no max).  The 100 is what I had when testing.

Will update the pull request to 5000.  This code change does not require
the nginx config be updated, that just allows the defaults to be set in the
config.  Will still work with old config.

**Comment by teharrison** [comment]
Forgot to mention, the max is a soft cap and not a hard cap. User #100
would cause there to be no provisioned containers, but user #101 would get
a container, just has to wait on it building.

**Comment by briehl** [comment]
I see, that's just how many are sitting around waiting. No problem, just clarifying that's what you wanted to pull.

**Pull request merged**
