### PR TITLE
Fix PTV-1717/-1839 - landing page link with functional-site prefix

### PR DESCRIPTION
**Pull request by eapearson**
# Description of PR purpose/changes

Some modeling widgets, such as the FBAModel viewer, were reported to have broken landing page links. The user reported that the link included "functional-site" in the path, and that removing it resulted in a working link for the landing page. "functional-site" was the name of the precursor to kbase-ui, which was in use about 5 years ago ... so this link has been broken for a long time!

The fix was very simple - just an edit of one line. The overall change required a tad more work, as the modeling widget source (kbase-extension/static/kbase/js/widgets/function_output/modeling) required some repair to be compliant with current practices in the codebase. To wit, it required fixes to satisfy eslint, including two overrides for global modules.

Two major flaws were left in the file, though, in order to avoid the need to refactor all of the modeling widgets - to wit, this code tends to use global modules, a practice which was superseded by AMD modules many years ago. The code does work, and converting all of the widgets to use or become good AMD citizens would require changing over 20 files, and involve hundreds if not thousands of edits.

Other caveats and notes:
- no additional tests were added; there is just one test for this file, loading the module; any functional tests would require much more work and surely some refactoring.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [x] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [x] Tests pass locally and in GitHub Actions
- [x] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_
 - screenshots included

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [-] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [-] Any dependent changes have been merged and published in downstream modules
- [x] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [-] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [-] [Version has been bumped](https://semver.org/) for each release
- [x] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Comment by eapearson** [comment]
Here is how the FBAModel viewer appears. An affected link is in the Genome line:

Screen Shot 2021-11-22 at 6 12 28 PM

Peeking into the markup, you can see the "functional-site" path component:

Screen Shot 2021-11-22 at 6 12 38 PM

Which leads to a broken landing page:

Screen Shot 2021-11-22 at 6 12 49 PM

The link after being fixed:

Screen Shot 2021-11-22 at 6 44 03 PM

**Comment by briehl** [comment]
@eapearson that single unit test is weird and cranky and has been disabled in a PR to the truss branch until we can refactor the test. Everything else passes, so I think this is fine.

**Review by briehl — APPROVED** [review]
Thanks for this. Those modules really need some rewriting, and this should help keep them moving along until we can do that.

**Comment by eapearson** [comment]
awesome, thanks.

**Pull request merged**
