### PR TITLE
Initial Tour

### PR DESCRIPTION
**Pull request by briehl**
Uses the Bootstrap Tour that's included with Jupyter.

Also introduces the dropzone requirement as a pre-req for drag and drop onto narratives... not likely to be used in this sprint, though.

### CODE REVIEW

**Comment by briehl** [comment]
Tagging @thebenallen and @nlharris - the file that'll be updated in the short term (I'll see if I can make it an external yaml file or something similar - is tour.js included in this PR. And I was wrong, it turns out you can include HTML if you want.

**Comment by nlharris** [comment]
Cool! Looking forward to trying it out.
That's good news that HTML can be included. Does that mean we can include hyperlinks to pages with more information?

**Comment by briehl** [comment]
You should be able to, I think.

**Comment by briehl** [comment]
I'll go ahead and merge this now so other eyes can see it. Now that Miriam's issue is (hopefully?) sorted, I'll start messing with the contrast on the tour panel.

I'll also pop the tour's markup out into a separate template for easier adjusting - I really just copied that tour script from Jupyter anyway without many changes.

**Comment by thebenallen** [comment]
@briehl Should we be seeing/testing the tour in Next? I don't see it in the hamburger menu there.

**Comment by briehl** [comment]
It's not on next yet, or CI either. I'll call for a CI deploy this morning.

**Comment by thebenallen** [comment]
Hrm, I saw it in the menu on CI!

--
Thanks,
Ben Allen

On Sep 7, 2016, at 1:03 PM, Bill Riehl <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not on next yet, or CI either. I'll call for a CI deploy this morning.

**Pull request merged**
