### PR TITLE
Updates to SampleSet Viewer: search

### PR DESCRIPTION
**Pull request by slebras**
# Description of PR purpose/changes

Updates SampleSet Viewer to include calls to SetAPI for search and sorting functionality of the table. Improves user experience. not a strict dependency but [this PR](https://github.com/kbaseapps/SetAPI/pull/40) for SetAPI would be good to include beforehand.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [ ] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)

# Testing Instructions
* Details for how to test the PR: 

To test these changes locally, start the local narrative with this branch using the normal `kbase-narrative` command. You'll have to navigate and have access to a SampleSet object in a narrative. Open the object viewer by clicking on the object in the data panel. navigate to the "samples" tab of the viewer and attempt to search for something in the search bar. Note: the object must be indexed by the index_runner in order for the viewer to work properly. If no data comes up, try another object. For testing purposes I used WS object `45700/57/1` which is indexed in elastic.

- [x] Tests pass in travis and locally 
- [x] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have run Black and Flake8 on changed Python Code manually or with git precommit (and the travis build passes)

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Comment by briehl** [comment]
@slebras 
Tests aren't passing for me. Here's the output I see from the sample set viewer tests:
```
FAILED TESTS:
  Test the kbaseSampleSet viewer widget
    ✖ Should properly render SampleSet
      Chrome Headless 86.0.4240.111 (Mac OS 10.15.6)
    Error: Expected '<div><div class="tabbable"><ul class="nav nav-tabs" data-id="tabs-nav"><li class="" style="white-space: nowrap;"><a href="#" data-tab="Summary">Summary</a></li><li style="white-space: nowrap;" class="active"><a href="#" data-tab="Samples">Samples</a></li></ul><div class="tab-content" data-id="tabs-content"><div class="tab-pane fade active"><div style="margin-top: 15px;"><table class="table table-striped table-bordered table-hover" style="margin-left: auto; margin-right: auto;"><tbody><tr><td>KBase Object Name</td><td><a href="/#dataview/45700/35/1" target="_blank">name</a></td></tr><tr><td>Saved by</td><td></td></tr><tr><td>Number of Samples</td><td>2</td></tr><tr><td>Description</td><td>This is a test sample set.</td></tr></tbody></table></div></div><div class="tab-pane fade"><div><div class="container-fluid" style="margin-top: 5px;"><div class="row" style="margin-bottom: 5px"><div class="col-md-4"><button class="btn btn-default btn-md"><span class="fa fa-caret-left"></span></but ... to contain 'madeup'.
        at <Jasmine>
        at test/unit/spec/function_output/kbaseSampleSet-spec.js:127:45
        at <Jasmine>
        at test/unit/spec/function_output/kbaseSampleSet-spec.js:126:23
```

**Comment by briehl** [comment]
@slebras can you share a CI narrative (or any other environment would be fine) with `wjriehl` with a SampleSet object to test with? Thanks!

**Comment by briehl** [comment]
I'm also seeing a bunch of minor things from both Codacy and SonarCloud. They're small, but please fix them when you can.

**Comment by eapearson** [comment]
I've incorporated these changes into a new effort to finalize the sampleset viewer. 
I'll post that up soon, and then we can close this.

**Pull request closed without merging**
