### PR TITLE
html for cell update

### PR DESCRIPTION
**Pull request by dangunter**

### CODE REVIEW

**Comment by eapearson** [comment]
Did you mean to include an entire bootstrap package? Will it conflict with the existing bootstrap? It should already be available as a module in the Narrative. Although we load bootstrap via modules, BS loads globally in the browser (styles and javascript), so the most recently loaded one will overwrite whatever was there before.

**Comment by briehl** [comment]
That's all just the standalone html mockups of the app cell changes we discussed yesterday. Should be safe. Maybe we shouldn't put it here, but in a separate page somewhere? Maybe narrative-dev?

**Comment by eapearson** [comment]
Yes, it isn't clear to me why we would incorporate mockups into the narrative...

**Comment by briehl** [comment]
It wouldn't be IN the narrative, just part of the repo for storage and a single point of communication and documentation. I suggested it to Dan, but now I'm rethinking that!

**Comment by scanon** [comment]
Did this get resolved?

**Pull request merged**
