### PR TITLE
[WIP] Reads view update

### PR DESCRIPTION
**Pull request by briehl**
Putting in some suggested changes, and getting it up to eslint snuff, and fixing errors.

### CODE REVIEW

**Comment by briehl** [comment]
Still needs better errors - should use the createErrorDiv function from util/display. Will do that soon.

**Comment by briehl** [comment]
Okay, I think this is ready. I also made a more, ahem, professional change to the palette icon (less rocketships, more chain link).

I altered the shape of the data icon for palette data, too. now it's a rounded square (same as app icons) instead of circle. Sound okay?
@psdehal @msneddon

**Comment by msneddon** [comment]
I think that looks good.

**Comment by briehl** [comment]
Ok. I'll merge it in, then. Gonna bump the version first.

**Pull request merged**
