### PR TITLE
Adding new Actions CI workflow

### PR DESCRIPTION
**Pull request by jsfillman**
## Jira Ticket / Issue #

- [DEVOPS-340](https://kbase-jira.atlassian.net/browse/DEVOPS-340)

## Description of PR purpose/changes

- Provides CI actions needed for process changes requested in [DATAUP-67](https://kbase-jira.atlassian.net/browse/DATAUP-67)

## Usage

From script comments:
```
# Usage: ./deploy_tag.sh IMAGE_TAG TARGET DEV_PROD
#
# Example 1: ./deploy_tag.sh latest ci dev
# Example 2: ./deploy_tag.sh pr-9001 next prod
#
# Where:
#   IMAGE_TAG is either the pull request (e.g. `pr-9001`) or `latest`
#   TARGET is one of: `appdev`, `ci`, or `next`
#   DEV_PROD is the source of the above IMAGE_TAG:
#     If set to `dev`, then the image will be pulled from the `APPNAME-develop` image
#     Otherwise, it'll pull the (pre)production `APPNAME` image
#
# Be sure to set $TOKEN first!
# See: https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
```

### CODE REVIEW

**Comment by jsfillman** [comment]
:rofl: at how much Codacy hates my proposal doc, but passing otherwise.

**Comment by briehl** [comment]
Codacy is really opinionated about markdown formatting that (mostly) doesn't translate when rendered. It's kinda funny.

**Review by briehl — APPROVED** [review]
This all looks good to me, especially since it's all been battle-tested in the narrative-traefiker repo. 👍

**Review by briehl — CHANGES_REQUESTED** [review]
Sorry, I mis-clicked the other review and can't see how to remove or change it.

Please add some instructions to the docs directory. Thanks!

**Comment by jsfillman** [comment]
Narrative deploy howto added in: docs/deploy_narrative.md

Full text for convenience:


## Narrative Development & Deployment HowTo


### Overview

1. Create a "development" image for CI.
1. Deploy image to CI.
1. Once tested in CI, create a single "production" image for appdev, next, & prod.
1. Tag the "production" image for deployment using the `deploy_tag.sh` script.
1. Deploy the "production" image in the relevant environments.

### CI

#### Create CI Image

1. Create a new temporary branch from the `develop` branch.
1. Add a _single_ bug fix or new feature to your temporary branch.
1. Create a new [pull request](https://github.com/kbase/narrative/compare) to merge your branch into `develop`.
1. Ensure the automated [build test](https://github.com/kbase/narrative/actions?query=workflow%3A%22Build+Test+Image%22) completes successfully.
1. Complete review and testing.
1. Merge pull request.

#### Deploy CI

Once a pull request is merged from a temporary branch to `develop` a new _development_ image will be available at:
`docker.pkg.github.com/kbase/narrative/narrative-develop:latest`

Simply restart the `narrative` container for CI in Rancher. No other action is needed.

### Appdev, Next, & Prod

#### Create Image

1. Create a new [pull request](https://github.com/kbase/narrative/compare) to merge the `develop` branch into `master`.
1. Follow the same process outlined in the `Develop` section above.

Once a pull request is merged from `develop` to `master` a new _production_ image will be available at:
`docker.pkg.github.com/kbase/narrative/narrative:latest`.


#### Tag & Deploy Image

1. Ensure the [deploy_tag.sh](https://github.com/kbase/narrative-traefiker/blob/develop/.github/workflows/scripts/deploy_tag.sh) script is installed on either your local workstation, or under your home directory on a secured system, such as `install.kbase.lbl.gov`.
2. Create a GitHub [personal access token](https://github.com/settings/tokens) and set it as "$TOKEN" in your workstation/server shell environment.
3. Run the `deploy_tag.sh` with the following syntax:
`./deploy_tag.sh -o "kbase" -r "narrative" -t "latest" -e "appdev"`
```bash
  Where:
    -o ORG is the organization (`kbase`, `kbaseapps`, etc.)
    -r REPO is the repository (e.g. `narrative`)
    -t IMAGE_TAG is the *current* Docker image tag, typically `pr-#` or `latest`
    -e TARGET Sets target environment's tag. This is typically either:`appdev`, `next`, or `prod`.
```
4. Restart the `narrative` container for the desired environment (e.g. `appdev`) in Rancher.


### Image URLs

| Evironment  | Image URL   |
| ----------- | ----------- |
| CI          | docker.pkg.github.com/kbase/narrative/narrative-develop:latest |
| Appdev      | docker.pkg.github.com/kbase/narrative/narrative:appdev         |
| Next        | docker.pkg.github.com/kbase/narrative/narrative:next           |
| Production  | docker.pkg.github.com/kbase/narrative/narrative:prod           |

**Review by briehl — APPROVED** [review]

**Pull request merged**
