### PR TITLE
Implement SCT-3038 refseq public data also search by genome_id and source_id

### PR DESCRIPTION
**Pull request by eapearson**
## Description of PR purpose/changes

* Please include a summary of the change and which issue is fixed.

Modifies the query backing the refseq public data panel so that searches are conducted against the scientific_name, genome_id, and source_id fields. The match is an ES version of "or", so that a match on any one of these fields will succeed.
Previously only scientific_name was considered.
genome_id,  shown. as "KBase ID", is the refseq assembly accession number, and source_id is the ncbi project accession number.

Integration tests added for searching a value in these new fields.

* Please also include relevant motivation and context.

This request was originally from Shane, who adds:

FYI.  This search change is actually related to a message we want to send out to users that had corrupt Euk genomes.  With out this fix it is difficult to explain to users how to find the right substitute.

* List any dependencies that are required for this change.

none

## Jira Ticket / Issue #

https://kbase-jira.atlassian.net/browse/SCT-3038
- [x] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

## Testing Instructions
* Details for how to test the PR:
- [x] Tests pass locally and in GitHub Actions
- [x] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [-] Any dependent changes have been merged and published in downstream modules
- [x] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [-] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Review by briehl — APPROVED** [review]
🎉

**Comment by briehl** [comment]
@eapearson there's been an issue with getting the integration tests working. I worked out the version mismatches, but now they consistently fail to get a session id. I'm not sure what's the issue there yet, and haven't had time to work through it. If you can now, great, if not, then I'll be satisfied if they run locally.

**Comment by eapearson** [comment]
> @eapearson there's been an issue with getting the integration tests working. I worked out the version mismatches, but now they consistently fail to get a session id. I'm not sure what's the issue there yet, and haven't had time to work through it. If you can now, great, if not, then I'll be satisfied if they run locally.

@briehl In this PR I did some work on the public data integration tests, and they now run cleanly for me every time locally. There were some runaway promises, which is usually the heart of the session id complaints. There was also some change in the state of CI search, so I needed to adjust some of the test data to match.
It looks like the tests did not run the first time around in the pull_request workflow (the others worked), but after pushing a minor change to make sonar cloud happier, they all ran fine.
I really hate JS integration testing frameworks, well, JS asynchronous junk.

**Comment by eapearson** [comment]
@briehl Is this ready for merging? There is urgency to get this merged, and then deployed (which deployment will also bring along the previous refseq search improvement, to 'AND' the terms together.)

**Pull request merged**
