### PR TITLE
DATAUP-202 Moves options menu to be first

### PR DESCRIPTION
**Pull request by bio-boris**
# Description of PR purpose/changes
* Moves options menu to be first

Before
image

After
image

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-202

# Testing Instructions
* Details for how to test the PR: 
- [ ] Tests pass in travis and locally 
- [ ] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [ ] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have run Black and Flake8 on changed Python Code manually or with git precommit (and the travis build passes)

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Review by briehl — COMMENTED** [review]
I think it's fine, but should there be a test for the button order? It would go in `test/unit/spec/narrative_core/kbaseCellToolbarMenu-spec.js`

**Review by eamahanna — COMMENTED** [review]
Is it possible to add tests to verify that the dropdown menu has the appropriate options based on the the input. i.e. `Show Code, Delete Cell, ect`

**Review by eamahanna — COMMENTED** [review]
Also, can you add an aria-label for the ellipsis button. The button is generated on line 277ish. The aria should describe the button i.e. `aria-label: 'cell options'`. this will provide greater context for people who use screen readers. Currently when a screen reader is on the button, all it says is ` popup button`, which doesn't provide a lot of context.

**Review by eamahanna — COMMENTED** [review]
All of the changes look good. I will approve once the codacy and sonar analysis are passing :) Nice job!

**Comment by bio-boris** [comment]
@eamahanna Thanks
Sonarcloud did not fail show any bugs so we are good to go
Codacy has some indentation errors, and code autoreformat doesn't fix it, and again there are no critical bugs so we are good to go

**Review by eamahanna — COMMENTED** [review]
@bio-boris I still think it is worth addressing the duplicated code and spacing. They should be quick fixes.

**Review by eamahanna — APPROVED** [review]

**Pull request merged**
