### PR TITLE
SCT-416 Add a couple simple log functions for metrics

### PR DESCRIPTION
**Pull request by briehl**
Currently only supports open and save narrative. 

Checklist before review:
- [x] Recover from socket failure
- [x] Re-open closed sockets as needed
- [x] Add log command to save and open segments of kbasewsmanager
- [x] Add test / local mode so devs don't spam logs (or maybe that's okay as we filter dev accounts? @sychan ?)
- [x] Tests!

### CODE REVIEW

**Comment by briehl** [comment]
Ok, all the things are added and probably ready to test on CI. Some caveats:
* there's now a new 'dev' block in the main config. This has the `log_host` and `log_port` keys set to `null` by default. change them to `localhost` and `9000` if you're following @sychan's flow for local testing with mini_kbase. Had to do a little semi-ugly hacking to get a couple other things working - other than the host and port, everything else in the 'dev' block points to CI. 'dev' it set by default.
* the other blocks are configured to talk to elasticsearch2.chicago.kbase.us:9000 for their log entries. I don't know if this'll work, since that can only be talked to from inside KBase, and maybe not KBase-berkeley. We'll see!

**Comment by scanon** [comment]
Looks good to me.  I'm inclined to merge it.

**Comment by briehl** [comment]
I have another PR pending for some cleanup for a new release. Let's merge this after that one gets merged and staged for next - I'd hate for it to hold up the next release if this breaks anything tragically.

**Comment by briehl** [comment]
master's now updated with the shiny new 3.6.0 version. We can pull this now (after I fix some conflicts).

**Pull request merged**
