### PR TITLE
split test functions in gha

### PR DESCRIPTION
**Pull request by briehl**
# Description of PR purpose/changes

Separates the test actions into unit test and integration test runs, so they can be more easily checked to see what passes and what fails. It maybe makes things take a little longer as the app has to get built multiple times, but I think it'll be helpful for seeing at a glance what's failing.

This came up from seeing a new batch of `dependabot` PRs which all failed miserably. This is really due to `dependabot` using a separate fork for submitting PRs - so another option might be to have the integration tests skip / fail immediately if there's no token available. Right now, they continue and just time out all over the place as they're running tokenless. The unit tests should be fine without authentication, and in fact, that's preferred.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [n/a] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [ ] Tests pass locally and in GitHub Actions
- [ ] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [n/a] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [n/a] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [ ] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Comment by ialarmedalien** [comment]
Are you already on the case of the codecov failure? PR looks fine otherwise.

**Comment by briehl** [comment]
Yeah, I'm on it. It's strange. I think it's a secrets issue, but I'm not sure how. 

I also noticed that the Python coverage file setup is wrong - it's making the wrong file! This led me down a little rabbit hole of switching from nosetests -> pytest in the Python stack, but that should probably be a different PR. Happily, that changeover was pretty much just swapping one for the other.

**Comment by briehl** [comment]
Looks like it's a new issue with Codecov.
https://github.com/codecov/codecov-action/issues/330 (opened yesterday) seems to be the same thing, public repos throwing that error.

I still want to go through with fixing the Python coverage stuff. But I'll do that in another PR.

**Review by ialarmedalien — APPROVED** [review]
These changes look fine; with any luck the codecov people will fix their side of the coverage problem so that the unit test workflow will pass.

**Pull request merged**
