### PR TITLE
Data source config.prod.json

### PR DESCRIPTION
**Pull request by kkellerlbl**
Current production data_source_config.json file.  I want to reconcile any differences, merge, then pull the new production file from the repo, so that it's no longer hand-curated.

Please review carefully before merging!

### CODE REVIEW

**Comment by kkellerlbl** [comment]
@qzzhang can you also review?  (Github isn't letting me add you as an explicit reviewer.)

**Comment by samseaver** [comment]
I don't think this is commit reads right, I think, but @qzzhang is really the one person who'd be best to comment on this.

**Comment by briehl** [comment]
The structure's fine, but I don't know what's changed recently to make sure that the various data endpoints are correct.

**Comment by qzzhang** [comment]
Sam was right.  In the "Current data_source_config.json from production", the "ci": {...} has the 'reference genomes' definition completely incorrect.  

If you want to reconcile and merge the data_source_config.json into a single file for all 3 environments, then 

1) keep the "ci": {...} from https://ci.kbase.us/data_source_config.json
2) keep the "prod": {...} from https://narrative.kbase.us/data_source_config.json
3) remove the  "genomes": {...} block from within "next": { "publicData": {...}...} because next has no RefSeq genomes at all.

**Comment by kkellerlbl** [comment]
@qzzhang or @samseaver can one of you fix the file and make a new PR?  I'll close this one since it's probably wrong.

**Pull request closed without merging**
