### PR TITLE
DATAUP-231 webdriverio example

### PR DESCRIPTION
**Pull request by briehl**
# Description of PR purpose/changes

In contrast with #1830 , this PR gives an example of using [webdriverio](https://webdriver.io) to run tests. This is built on Selenium and uses the WebDriver control mechanisms. Selenium was a bear to set up and make consistent with other things in the narrative repo. Also, wdio is currently used in the https://github.com/kbase/kbase-ui repo.

To set up:
* `npm install` to get dependencies
* edit `test/integration/wdio.conf.js` to add a CI auth token to the `kbaseToken` key
* run tests with `npx wdio test/integration/wdio.conf.js`. The drivers are very very version specific and will want Chrome v86.

This isn't necessarily meant to be merged, but as a discussion to contrast with #1830 that @eamahanna kindly provided. The goal here is to finish up the integration test framework ADR from #1832.

# Jira Ticket / Issue #
e.g. https://kbase-jira.atlassian.net/browse/DATAUP-X
- [x] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)

# Testing Instructions
* Details for how to test the PR: see above
- (n/a) Tests pass in travis and locally 
- (n/a) Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by bio-boris** [comment]
What should we think about when reviewing this ticket?

**Comment by briehl** [comment]
> What should we think about when reviewing this ticket?

Mostly, does it work, does the syntax make sense, do you think you could build on it with other integration tests.
FWIW, I think we're mostly decided on this as the main framework to use. This PR may get closed, however, and a new one opened with some more official testing. Or we can just keep some preliminary changes here and fold it in.

**Comment by briehl** [comment]
Before merging, I would like to keep codacy happy, which'll mean moving/removing `test/integration/README.md` and some other minor tweaks.

**Comment by briehl** [comment]
This has pretty much served its purpose as an example. Gonna close this PR and focus on getting it working through Travis-Ci in a separate branch/ PR.

**Pull request closed without merging**
