### PR TITLE
Vis cell refactor (resolving @eapearson conflicts)

### PR DESCRIPTION
**Pull request by briehl**
Whenever I see `fsm.js` I read `flying_spaghetti_monster.js`
(yes, I know it's finite state machine. 😄 )

### CODE REVIEW

**Comment by briehl** [comment]
@eapearson does this look right? There were a few conflicts with your changes in that last PR, and I didn't want to just overwrite things...

**Comment by eapearson** [comment]
Sorry, I guess I forgot to pre-merge in upstream :(

**Comment by eapearson** [comment]
i prefer flying spaghetti monster, now there's a logo.
My git skills are only just barely proficient, so I don't know exactly how to determine what you had to change to resolve the conflict, but I presume the changes were relatively minor and it still works, and any problems can be fixed, so I say go ahead, or did you want me to do it?

**Comment by briehl** [comment]
Nah, was just hoping you could check. Writing directly to the branch just makes me nervous now.
I'll just merge and deal with whatever breaks. FWIW, I've been hacking along with the changes for the past little while, and they all seem okay.

**Pull request merged**
