### PR TITLE
Updating so that Phytozome genomes appear in other environments

### PR DESCRIPTION
**Pull request by samseaver**
This is a simple change, but needs to be done before PAG (mid-January)

### CODE REVIEW

**Comment by briehl** [comment]
Just verifying that there's no more "Plant Genomes" now, just "Phytozome Genomes" now? 

Also tagging @kkellerlbl - that file should just live in webroot (e.g. narrative.kbase.us/data_source_config.json), and I'm not sure how it's deployed now with the new new changes.

**Comment by samseaver** [comment]
Given that the RefSeq genomes and (at a later date) the Ensembl genomes will contain plant genomes, we're better off naming them by their sources.

**Comment by kkellerlbl** [comment]
Right now the file is deployed out of a config directory which is not updated by a deploy.  So we'll need to put this file in place by hand.  I'll make a note of it for Thursday.

**Comment by kkellerlbl** [comment]
Will it break anything to put this file into production today?

**Comment by samseaver** [comment]
No. At worst, a user who may have been expecting to see "Plant Genomes" in the drop-down box, from past experience, would now see "Phytozome Genomes" instead.

**Comment by kkellerlbl** [comment]
I've put this on ci.  @samseaver can you check it out and make sure it works as you expect?  If it looks fine I'll propagate it to the other environments.

**Comment by kkellerlbl** [comment]
You may need to restart your narrative container.

**Comment by samseaver** [comment]
So, it's "working" in CI, but it had already been that way for CI (the changes were for next and production/appdev) so for CI, I don't see any change in behavior.

**Comment by kkellerlbl** [comment]
Okay, I've just updated next.  You may need to restart your container there too.

**Comment by samseaver** [comment]
Ya that worked

**Pull request merged**
