### PR TITLE
DATAUP-754 Dependabot, python

### PR DESCRIPTION
**Pull request by n1mus**
# Description of PR purpose/changes

Did recommended upgrades for:
* `idna`
* `pyopenssl`
* `pymongo`
* `jupyter-console`
* `beautifulsoup4`
* `plotly`
* `pygments`
* `html5lib`

Did intermediate version upgrade instead for:
* `cryptography` (in order to satisfy `pyopenssl` upgrade but avoid python3.6 support drop)

Rejected recommended upgrades for:
* `jinja2` (and actually downgraded)
* `pillow`
* `pytest` (so negating a recent dependabot PR rebase)

Additional non-dependabot downgrades:
* `jsonschema` (just the start of a rabbit hole)

# Jira Ticket / Issue #

Related Jira ticket: https://kbase-jira.atlassian.net/browse/DATAUP-X
- [x] Added the Jira Ticket to the title of the PR (e.g. `DATAUP-69 Adds a PR template`)

# Testing Instructions
* Details for how to test the PR:
- [ ] Tests pass locally and in GitHub Actions
- [ ] Changes available by spinning up a local narrative and navigating to _X_ to see _Y_

# Dev Checklist:

- [x] My code follows the guidelines at https://sites.google.com/lbl.gov/trussresources/home?authuser=0
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] (JavaScript) I have run Prettier and ESLint on changed code manually or with a git precommit hook
- [ ] (Python) I have run Black and Flake8 on changed Python code manually or with a git precommit hook
- [ ] Any dependent changes have been merged and published in downstream modules

# Updating Version and Release Notes (if applicable)

- [ ] [Version has been bumped](https://semver.org/) for each release
- [x] [Release notes](/RELEASE_NOTES.md) have been updated for each release (and during the merge of feature branches)

### CODE REVIEW

**Comment by ialarmedalien** [comment]
It looks like something strange is going on in the docker image wrt: the backend tests -- have a look at the logs for the [`run_unit_tests`](https://github.com/kbase/narrative/runs/6302254595?check_suite_focus=true) backend tests step. Unfortunately `pip` has some quirks and when it installs a list of modules, it doesn't always catch all the dependencies of the listed modules, plus whether or not the deps get installed can be dependent on where in the `requirements.txt` file a module is listed (😖 ).

Previously we had a similar issue with `pytest` not being able to find one of its component modules which was fixed by moving `pytest` to the end of the file. It may be that you just need to add `pluggy` to the `requirements.txt` file.

**Comment by ialarmedalien** [comment]
It looks like something strange is going on in the docker image wrt: the backend tests -- have a look at the logs for the [`run_unit_tests`](https://github.com/kbase/narrative/runs/6302254595?check_suite_focus=true) backend tests step. Unfortunately `pip` has some quirks and when it installs a list of modules, it doesn't always catch all the dependencies of the listed modules, plus whether or not the deps get installed can be dependent on where in the `requirements.txt` file a module is listed (😖 ).

Previously we had a similar issue with `pytest` not being able to find one of its component modules which was fixed by moving `pytest` to the end of the file. It may be that you just need to add `pluggy` to the `requirements.txt` file.

**Comment by briehl** [comment]
That's silly. Maybe the version of `pluggy` gets overwritten by something else? I ran things in my local env, and it seemed to test ok, I'll try in a fresh env.

**Comment by ialarmedalien** [comment]
looks like there were a couple of issues:
https://github.com/kbase/narrative/runs/6302185929?check_suite_focus=true#step:7:1099
https://github.com/kbase/narrative/runs/6302185929?check_suite_focus=true#step:7:1798

so I'd revert those two deps back to the old version and see if that changes anything.

If you also rebase on develop, there's a test fix which should get the FE unit tests passing again

**Comment by ialarmedalien** [comment]
redo the current commits so that commit 1 updates the release notes with the updates from dependabot, and then, in a separate commit, see if you can add `idna`. If that works, update `pyopenssl`, and after that, `pymongo`. If it doesn't, try updating `pyopenssl` or `pymongo`. If none of that works, we can just merge the first commit with the updated release notes.

**Comment by n1mus** [comment]
I did not realize that the narrative still runs on python3.6. It was hard to tell from the Dockerfile and I guess it's not common to have narrative containers around since the base image is so large.

**Comment by briehl** [comment]
We really need to update the base image. I think maybe we should start one from scratch. I'm not sure that there are things in the KBase base image that are necessary. Though there might be a new one these days.

**Comment by ialarmedalien** [comment]
ISTR that digging into the narrative image and following the trail of the various docker images that it is based on takes you down through all nine circles of hell.

**Comment by briehl** [comment]
Yup, been there. I think we could safely put it off for now.
Well, "safely" anyway.
Until something dire breaks and no longer installs.

**Pull request merged**
