### PR TITLE
updated app cell dependencies

### PR DESCRIPTION
**Pull request by msneddon**

### CODE REVIEW

**Comment by briehl** [comment]
Great. Thanks! But there are also a couple other dependencies - the kbaseNarrativeOutputCell (at line 948, and one other) and kbaseAccordion (line 151). These should be added, too.

**Comment by msneddon** [comment]
Ah ok.  I'll add those too.

**Comment by msneddon** [comment]
I assume we don't need to include kbaseNarrativeError because that widget is not invoked here, just passed on to the NarrativeOutputCell widget?

**Comment by msneddon** [comment]
also removed the Handlebars input parameter to the method cell widget...

**Pull request merged**
