### PR TITLE
bug fixes to some javascript widgets

### PR DESCRIPTION
**Pull request by teharrison**
Bug fixes to widgets that were producing confusing or incorrect output based on different uses.
Resolve this tickets:
https://atlassian.kbase.us/browse/NAR-699
https://atlassian.kbase.us/browse/NAR-700

### CODE REVIEW

**Comment by briehl** [comment]
Is that a whole new version of jquery.svg.js? Will that affect anything else?

**Comment by teharrison** [comment]
It just 5 lines or so changed, but somehow the file was used in two
different editors and suddenly all the indentations changed.  I can try and
re-edit it be hand based on the previous changes to show it properly if
that would help.

**Comment by briehl** [comment]
Nope, that's fine. This looks safe and important enough to merge in now. I'll get it deployed on -dev now, and later on the admin team will deploy to -test.

But we'll need plenty of testing and final approval from Adam and Fernando to move to production.

**Comment by samseaver** [comment]
You can append the github url with ?w=1 to ignore indentation and
whitespace:

https://github.com/tiimgreen/github-cheat-sheet#ignore-whitespace

On Mon, Feb 16, 2015 at 5:28 PM, Travis Harrison <notifications@github.com>
wrote:

> It just 5 lines or so changed, but somehow the file was used in two
> different editors and suddenly all the indentations changed. I can try and
> re-edit it be hand based on the previous changes to show it properly if
> that would help.
>
> On Monday, February 16, 2015, Bill Riehl <notifications@github.com> wrote:
>
> > Is that a whole new version of jquery.svg.js? Will that affect anything
> > else?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/narrative/pull/294#issuecomment-74583386>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/narrative/pull/294#issuecomment-74589532>.
>



-- 
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Pull request merged**
