### PR TITLE
Git Workflow ADR DATAUP-62

### PR DESCRIPTION
**Pull request by eamahanna**
# Description of PR purpose/changes

The purpose of this PR is to create an ADR to document the git workflow developers will use to contribute to the narrative repo.

NOTE: Please feel free to comment and add additional reasons for a given alternative or disagreements. 

# Jira Ticket / Issue #
https://kbase-jira.atlassian.net/browse/DATAUP-62
- [ x] Added the Jira Ticket to the title of the PR e.g. (DATAUP-69 Adds a PR template)

# Testing Instructions
N/A

# Dev Checklist:

- [ x] My code follows the guidelines at https://sites.google.com/truss.works/kbasetruss/development
- [x ] I have performed a self-review of my own code
- [N/A ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [N/A  ] I have added tests that prove my fix is effective or that my feature works
- [ N/A ] New and existing unit tests pass locally with my changes
- [ N/A ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ialarmedalien** [comment]
LGTM!

**Comment by bio-boris** [comment]
LGTM. By the way you can just click the checkboxes you don't have to write X in them.

**Comment by briehl** [comment]
This all sounds very reasonable! My only request is that we lock the develop and master branches (and / or other primary deploy branches) to only get updated via externally approved pull request. Which I think they already are, but I'm not sure if that needs to go in the ADR.

**Comment by leia-sefkin** [comment]
LGTM 👍

**Comment by ialarmedalien** [comment]
@briehl 

> This all sounds very reasonable! My only request is that we lock the develop and master branches (and / or other primary deploy branches) to only get updated via externally approved pull request. Which I think they already are, but I'm not sure if that needs to go in the ADR.

What do you mean by "externally approved pull request"? PR approval by a codeowner (does this repo have code owners?)?

**Comment by MrCreosote** [comment]
BTW you can make actual checkboxes for the checklist rather than just ascii: https://docs.github.com/en/github/managing-your-work-on-github/about-task-lists

**Comment by leia-sefkin** [comment]
One thing I have a question about (may be something to discuss with Jason/DevOps on Tuesday) - did you all discuss how much we care about preserving individual commits on branches vs. squashing (through interactive rebase) before merging? 

From past experience I know a little easier from a release management perspective to roll back or troubleshoot if bug fixes or other smaller commits are squashed. 

At the same time it's an extra step in the process, and there may be other strategies folks prefer (I am not a git/devops wizard 🧙 )

**Pull request merged**
