### PR TITLE
Update staging in prep for release 1.0.3

### PR DESCRIPTION
**Pull request by briehl**
There have been numerous changes since the last release back in February. These are pretty well described in the Release notes here: https://github.com/kbase/narrative/blob/95aa2e6834ce8ee1fdec0bc43041702ddfbe7501/RELEASE_NOTES.md

Some high level ones that explain the number of files being changed:
1. Updated all Javascript code to be loaded via Require.js
2. Updated HTML files to ditch the long list of scripts
3. Added bindings to use Travis-CI for testing
4. Added some initial tests

Details and closed tickets are in the release notes.

### CODE REVIEW

**Comment by kkellerlbl** [comment]
I don't need to look at every single change, do I?  ;-)

I'll merge in a few minutes.  Let me know when you want the -next deploy.

**Comment by briehl** [comment]
Let's do that tomorrow. Will you be at Emeryville?

**Comment by kkellerlbl** [comment]
Yes, I'll be there.

**Comment by eapearson** [comment]
Bill, I’ve sure you’ve seen the late breaking minor hotfix PR for ui-common develop. It is just two lines to re-enable jquery-ui to un-break the data type viewers. Low risk, but we should look for signs of weirdness in bootstrap. Ignorant I had disabled it back in March because it didn’t seem to be used (thought he), yet was conflicting with bootstrap.

Erik.

**Comment by kkellerlbl** [comment]
If it's in ui-common develop, it should get deployed in -ci later today when the pending PR to narrative:develop is merged.  If it looks good and safe, we can do a PR for ui-common:develop->staging before I redeploy narrative-next tomorrow.

**Comment by briehl** [comment]
I just merged a couple little PRs into ui-common:develop, including breaking the rules and merging one I that I made, so we can get them visible on -ci. I won't do it again, I promise! (it was really small, mainly removed "prototype" from the header).

**Pull request merged**
