### PR TITLE
font-awesome icons uber alles

### PR DESCRIPTION
**Pull request by dangunter**
Put FA icons everywhere I could find (data and methods).

https://www.dropbox.com/s/3zsshqv6rip23ze/Screenshot%202015-01-29%2006.38.34.png?dl=0

### CODE REVIEW

**Comment by dangunter** [comment]
more screenshots

screenshot 2015-01-29 11 44 28
screenshot 2015-01-29 11 44 45
screenshot 2015-01-29 11 44 59

**Comment by briehl** [comment]
Those look pretty good to me! Any comments from anyone else, or should we just jump in and merge this?

**Comment by dcchivian** [comment]
no wait!  I'm working on selecting icons!

- dylan

**Comment by psdehal** [comment]
Let's merge it

**Comment by samseaver** [comment]
I love them, but we can't use a "tree" for phylogenetic trees. It's a
plant, technically, and it'll be confusing for plant biologists.

On Thu, Jan 29, 2015 at 1:54 PM, psdehal <notifications@github.com> wrote:

> Let's merge it
>
> On Thu, Jan 29, 2015 at 11:52 AM, Bill Riehl <notifications@github.com>
> wrote:
>
> > Those look pretty good to me! Any comments from anyone else, or should
> we
> > just jump in and merge this?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kbase/narrative/pull/223#issuecomment-72092114>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kbase/narrative/pull/223#issuecomment-72092428>.
>



-- 
Postdoctoral Fellow
Mathematics and Computer Science Division
Argonne National Laboratory
9700 S. Cass Avenue
Argonne, IL 60439

http://www.linkedin.com/pub/sam-seaver/0/412/168
samseaver@gmail.com
(773) 796-7144

"We shall not cease from exploration
And the end of all our exploring
Will be to arrive where we started
And know the place for the first time."
   --T. S. Eliot

**Comment by dcchivian** [comment]
I agree (about the tree).  working on it...

**Comment by briehl** [comment]
I'm going to go ahead and merge this so it can get deployed on narrative-dev. I imagine there will still be a round or two of changes, but that's okay!

**Pull request merged**
