### PR TITLE
Job related changes and other fixes

### PR DESCRIPTION
**Pull request by eapearson**
- job cancellation invokes request-job-cancellation (which does nothing yet)
- back end job status events split into job_status and job_status_all
  - this allows the "detection of deleted job" in the job panel to work since the logic requires that all known jobs be included in the message (which is what job_status_all is for)
  - this is a [wip] but fixes a problem with new jobs issuing a job-deleted message
- fixes to properly remove event handlers

### CODE REVIEW

**Comment by eapearson** [comment]
Oh, and a placeholder "summary widget" for app cell job status -- this should become the same one displayed in the app cell and in the toolbar when the app cell is collapsed. This is basically the job status in a single line box  for the nth time.

**Comment by eapearson** [comment]
Just noticed my console is flooding. Working on it...

**Comment by eapearson** [comment]
This PR now includes updates to the subdata widget. This should be ready to merge now.
Still to do includes the incorporation of default(s) into the available items. Will work on that next.

**Comment by briehl** [comment]
I'm not sure why the tests are still failing. It's apparently not providing a few dependencies correctly.

**Comment by briehl** [comment]
Eh. All better. I blame cosmic rays.

**Comment by eapearson** [comment]
Thanks, I was waiting for the new build to finish -- it may have been the ever-troublesome phantomjs. It could not find some js libs which really should have been there. There is one quirk of phantomjs which reared its head in the past, I see that the package.json requires ^1.9.17, and I know that the problems (js bugs) were fixed late in the 1.9 series and in 2+. Since this version spec is not deterministic, we don't really know which phantomjs may be installed (+ the upstream repo has problems.)

**Comment by briehl** [comment]
Since that's only used for testing, we should just bump it to the 2+ series, or whatever version is most stable.

**Pull request merged**
