### PR TITLE
Fix compiler loadtime

### PR DESCRIPTION
**Pull request by briehl**
Should actually fix the page load timing. Works on narrative-dev with lots and lots of page refreshes.

### CODE REVIEW

**Comment by msneddon** [comment]
I think there is still something in a require config that is searching for static/narrativeMain.js?

I'm getting a 404 on trying to find that resource on the backend and in the browser:
2015-08-11 13:57:49.048 [tornado.access] WARNING | 404 GET /static/narrativeMain.js (127.0.0.1) 0.63ms

Would any of the tests catch that?  Because it did pass tests.

**Comment by briehl** [comment]
Grr. I think some commits got crossed that shouldn't have been. Thanks for catching that.

**Comment by briehl** [comment]
Ok, that should be fixed now. The problem was I was only testing the compiled version, not the uncompiled. The compiler saw what the paths were just fine, but they were off in the main page.

**Comment by msneddon** [comment]
Great.  It looks like it all loads correctly now, and basic things work, so I'm accepting.

**Pull request merged**
