### PR TITLE
refactor app panel using more narrative_service

### PR DESCRIPTION
**Pull request by Tianhao-Gu**

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@briehl Could you take a look?

**Comment by briehl** [comment]
All of the service packages are being displayed as "undefined"
Screen Shot 2019-04-29 at 3 21 21 PM

**Comment by Tianhao-Gu** [comment]
@briehl Thanks. I found the cause of 'undefined' category and also there was no icon for each app. 

https://github.com/kbaseapps/NarrativeService/pull/62

**Comment by Tianhao-Gu** [comment]
@briehl icons and categories are back 🤞 

Screen Shot 2019-04-30 at 2 02 02 PM

**Comment by briehl** [comment]
Looks good!

**Pull request merged**
