### PR TITLE
Fix copying workflow in view only mode

### PR DESCRIPTION
**Pull request by briehl**
See https://kbase-jira.atlassian.net/browse/KBASE-5008

### CODE REVIEW

**Comment by briehl** [comment]
Any complaints if I merge this? @eapearson want to review?

**Comment by eapearson** [comment]
I've noticed more Handlebars templates showing up. Is that the direction we're moving in for markup in code or just a personal preference? It is definitely an improvement over markup through jQuery, at some cost elsewhere.

**Comment by briehl** [comment]
For the record, I know there are a ton of libraries out there we could use to handle templating. Nunjucks is/was in there for a while on the kbase-ui side. Handlebars was in there, as well, for other uses, so I've been sticking with it in the Narrative. I would like to move away from plopping HTML code directly in Javascript, though, however we do it. There will be an extra cost of event binding, etc., but I feel it's something we should try for going forward.

**Comment by briehl** [comment]
Ok. I'll merge and rebuild on Jenkins.

I would also like to explore using React in the narrative, since it's another interesting solution to the problem, and it would also (probably) serve 3rd party devs who want to make widgets with something more modern than pure ES 5. Web components are a good idea, too.

Still, I think we should continue this discussion elsewhere.

**Pull request merged**
