### PR TITLE
lua changes from next

### PR DESCRIPTION
**Pull request by kkellerlbl**
Commit changes currently deployed on next.

### CODE REVIEW

**Comment by briehl** [comment]
Is this the change that would fix all containers being lost on redeploy? Or is it just catching up to non version-tracked things?

**Comment by scanon** [comment]
I think this is mainly the lost containers.

**Comment by kkellerlbl** [comment]
It's actually both.  These files were on next03 but nowhere else, and the lost narrative connection fix is in there (the notelauncher.lua changes).

**Comment by briehl** [comment]
Oh! I see what it's doing now. Yeah, that's great. Thanks for the fix.

**Pull request merged**
