### PR TITLE
Staging area panel

### PR DESCRIPTION
**Pull request by briehl**
A bunch of requested changes here:
* Remove multiple scrollbars
* Add "beta" to a few places, tweaked drag and drop text
* Created a config file to set available uploader apps and what params they should use
* Fixed problem where controls on successive pages of the file table didn't work/weren't rendered properly
* Added missing bulk import link to hamburger menu

### CODE REVIEW

**Comment by briehl** [comment]
Thanks for catching that. I meant to link it to the app panel for the specs it uses, and didn't quite finish that yet. Hold off on merging this, please.

**Comment by briehl** [comment]
This now links to a new API wrapper utility that uses the currently selected tag for fetching app specs.

**Comment by scanon** [comment]
I think this is fine.  @eapearson can you give it a quick review or should we let Bill go for it?

**Comment by briehl** [comment]
I'm going for it!
But there's a caveat - the genome uploader will not work for now. I'm making a ticket for that and sending it to @rsutormin and Tian.

**Pull request merged**
