### PR TITLE
Add conda support

### PR DESCRIPTION
**Pull request by jayrbolton**
This updates some of the build process and documentation focusing on Conda, which might be simpler for new users. It adds some documentation in the README.md as well.

This doesn't include the whole CLI module that I mentioned, so it's a smaller update

This repo generates/modifies a handful of config files that maybe could be gitignored that I wanted to ask about:
- src/biokbase/**/test.cfg -- can we call the committed one `test.example.cfg` and ignore this one?
- src/config.json -- can we call the committed one config.example.json and ignore this one?
- test/unit/testConfig.json -- same as above

### CODE REVIEW

**Comment by jayrbolton** [comment]
cc @briehl

**Comment by jayrbolton** [comment]
I'm going to add some more docs around testing

**Comment by jayrbolton** [comment]
Here is the CLI module I set up before but didn't include here: https://github.com/jayrbolton/narrative/blob/add-conda-support/src/cli.py. A couple things didn't work yet and I didn't want to spiral on it. Wanted to link it here in case we ever wanted to revisit the idea.

**Comment by jayrbolton** [comment]
Rendered version of the updated README.md: https://github.com/jayrbolton/narrative/blob/add-conda-support2/README.md

**Comment by sychan** [comment]
@jayrbolton Looks like there are conflicts - they may have come in when I merged in the dockerize branch. Do you want to try merge and resolve against the current develop branch?

**Comment by jayrbolton** [comment]
@sychan Yeah, I can work on resolving and seeing if any of the updates I made are still useful

**Comment by jayrbolton** [comment]
I guess this can be closed for now. I have not yet grokked all the layers of the docker setup.

**Pull request closed without merging**
