### PR TITLE
DATAUP-195 Integration Testing Framework ADR

### PR DESCRIPTION
**Pull request by eamahanna**
# Description of PR purpose/changes

This ADR selects an integration and end-to-end testing framework. Adding integration and e2e tests will provide additional test coverage and development confidence. 

# Jira Ticket / Issue #
https://kbase-jira.atlassian.net/browse/DATAUP-195

# Testing Instructions

No code changes

# Dev Checklist:

No code changes

# Updating Version and Release Notes (if applicable)

N/A

### CODE REVIEW

**Comment by dakotablair** [comment]
Before accepting this decision, I would like to see some tests written and included in the Travis build process so that they continue to be "actively used" by developers going forward whether they are familiar with integration testing frameworks or not.

Going forward it would be good to have a plan to reimplement the extant Selenium tests in Cypress and either remove Selenium completely or bring it up to the level of being "actively used" in the project. Having multiple integration test frameworks contributes to the steep learning curve of narrative development.

The limitations of Cypress in comparison to Selenium are a concern, but not enough to prevent its use. I am not familiar with Cypress, but I am concerned about whether it will be as functional as we need it to be to test complex user stories in the narrative framework.

One other consideration is community support. I know Selenium has it, but I would like to hear more about Cypress community support and major projects using Cypress.

**Comment by eamahanna** [comment]
Thanks @dakotablair for providing feedback! The intent of this branch is just to allow other developers to see what Cypress is and mess around with it. I do not intend on ever merging this branch.

If we choose to go forward Cypress, I anticipate the change would be implemented incrementally with the following steps:

Determine what work flows are actively being tested by selenium in the narrative repo
Implement Cypress to work locally, and to cover the existing selenium test cases
Get the cypress tests running in Travis
Remove selenium from the repo
What functionality are you concerned that Cypress may not cover?

For the cypress community, I believe it is fairly large and growing. Internally at Truss we use it on most of our projects. For larger projects, cypress lists some companies who use it. The companies are listed on their web site at the bottom of the page. . A couple of the larger companies they list are: Adobe, Disney Studios, Shopify, AutoDesk, Johnson & Johnson and Betterment. Are you looking for more specific examples?

**Comment by briehl** [comment]
Ok, lots to talk about here!

First, of the 3 options (selenium vs. cypress vs. no integration/e2e testing), I'd vote right away and pretty hard for doing SOME integration testing. I think not doing it has been a Bad Thing that's been happening for too long, and any form of repeatable integration testing would be a benefit.

**Comment by dakotablair** [comment]
I agree wholeheartedly with Bill that active integration testing is a Good Thing and if the choice is Cypress or nothing then we definitely want to go with Cypress.

That seems like a good plan, and my hope is to see some of it executed by the time this decision is made.

As far as the functionality of Cypress, you mentioned that its iframe support was limited, and the narrative uses iframes in certain cases.

I tend to desire more specificity, particularly with the projects themselves. I'm sure it will not be hard to find a similar project, I just have not taken time to do so yet. In terms of JavaScript, this project has somewhere around 200k lines of code, and it would be nice to Cypress implemented in a similarly sized project.

**Comment by eamahanna** [comment]
@dakotablair Here are a number of open source projects that use Cypress: [Cypress Open Source Projects](https://docs.cypress.io/examples/examples/projects-media.html)

**Review by briehl — APPROVED** [review]

**Comment by briehl** [comment]
I'll have more thoughts and comments, but I'm ok with merging this now. 👍

**Pull request merged**
