### PR TITLE
UI improvements for input error handling, job log [wip]

### PR DESCRIPTION
**Pull request by eapearson**
- add warning condition for input validation
- allow duplicate output object name with warning (but error if not same type)
- add error id to pave the way for error help (and testing)
- job log (get latest entries) off by one error and ui improvements

Lets not quite merge this until later today -- I want to review the errors for all the input widgets to ensure that these changes (a) don't break them and (b) can be updated to the new format.

### CODE REVIEW

**Comment by briehl** [comment]
is this ready to merge? I know it has a bunch of fixes.

**Comment by eapearson** [comment]
sorry, this will be ready within the hour.

**Comment by eapearson** [comment]
There is still more work in this area, which I'll keep working on today, but I think this is worth merging in.

**Comment by briehl** [comment]
Okay, let's merge.

**Pull request merged**
