### PR TITLE
prevent successfully completed app from re-inserting deleted output cell upon reload [SCT-791]

### PR DESCRIPTION
**Pull request by eapearson**
- also some code cleanup and removal of long-unused features
- note that the narrative must be saved after the output cell is deleted

### CODE REVIEW

**Comment by eapearson** [comment]
Hi @thomasoniii I added you as a reviewer so we could move this one along too. It is an important usability fix especially important for large narratives like the ones Miriam is working on now, because it prevents output cells from popping back into place after being deleted.

I'm going to spend the rest of the afternoon getting a handle on narrative testing, see if I can add a test for the various cases of output cell behavior.

BTW in case you don't use it enough to remember, to get rid of the whitespace formatting noise (it was too late when I noticed it) you can add ?w=1 to the end of the url when viewing the diff and it will remove all just-whitespace diffs.

**Comment by eapearson** [comment]
Hi @thomasoniii would you mind reviewing this? Then let me know and I'll ask Shane or Steve to merge it.

**Comment by thomasoniii** [comment]
Looks reasonable to me.

**Comment by eapearson** [comment]
@sychan or @briehl would you mind having a look and merging?

**Pull request merged**
