### PR TITLE
method -> app renaming refactor, improved fsm messages

### PR DESCRIPTION
**Pull request by eapearson**
It was finally time to bite the bullet and ensure that confusing references to "method" are replaced with "app".  Many many files were changed, sorry about that.
In addition, in order to handle the job state transition from something -> completed, the fsm message mechanism was adjusted to emit just before and after a state change, as well as when the state is initially set. This makes state change events much easier to configure and reason about.

### CODE REVIEW

**Comment by eapearson** [comment]
please don't accept this yet, output saving (the list of outputs stored in the app cell) is broken atm.

**Comment by eapearson** [comment]
okay, that is fixed now.

**Comment by briehl** [comment]
ready to merge?

**Comment by eapearson** [comment]
yes

**Pull request merged**
