### PR TITLE
Expression matrix uploader is added into Narrative UI

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by briehl** [comment]
Looks good to me. Does this need anything else to get the uploader working? Is there a widget or something needed for the upload panel?

**Comment by rsutormin** [comment]
There are 3 more things already done in CI but not in production yet:
1) Transform script (https://github.com/kbase/transform/pull/154) merged into develop branch
2) Registration of expression module in WS (KBaseFeatureValues)
3) Uploader method spec (https://github.com/kbase/narrative_method_specs_ci/tree/master/methods/import_expression_tsv_file) + type spec (https://github.com/kbase/narrative_method_specs_ci/tree/master/types/KBaseFeatureValues.ExpressionMatrix)

**Comment by briehl** [comment]
Ok. I'd like to have another round of testing of what's currently in the narrative on CI, then promote the current develop to staging (for the release next week). Then merge this in to develop, since it won't be part of next week's deploy.

Would you (and anyone else who reads this...) mind trying things on narrative-ci to see if it still works? Things work well for me, but I'd like to see more eyes on it.

**Comment by msneddon** [comment]
Sounds good, but let's try to do this round of testing quickly.  We need the uploader in CI soon to allow people to start testing new narratives methods.

**Comment by rsutormin** [comment]
Well, guys, I don't see my changes in Narrative deployed on CI yet. When is it going to be deployed?

**Comment by kkellerlbl** [comment]
Roman, it won't be deployed till the PR is merged.  It sounds like Bill wants more testing of what's already on -ci first, so that can be merged to staging, before merging your PR.

I've still been having some funny issues when a new deploy is done; sometimes it takes a while for my instance to come up, sometimes it's fine.  I haven't been able to reliably repeat it, though, and once it settles it seems fine, so I don't think it's something that would prevent merging to staging.  Other than that, I've been opening narratives on -ci a lot with no problems, but haven't run any jobs.  I'll run some today to see what happens.

**Comment by rsutormin** [comment]
By the way, guys, I don't think it's dangerous to merge this change because as long as specs are not visible in production (they aren't there) import item isn't visible and added javascript code is not reachable.

**Comment by rsutormin** [comment]
One thing is still broken in CI (but it's functional site though). Method specs don't show up:
https://narrative-ci.kbase.us/functional-site/#/spec/module/KBaseFeatureValues

**Comment by briehl** [comment]
@rsutormin - I wasn't aware of that spec update. That might be okay. The other problem you saw with the method specs is an with ui-common. Erik said he'd update that soonish.

@kkellerlbl  - What do you mean for your instance to come up? Which loading step is it getting caught at? The 3-bubble gif means that the instance is spinning up (which always takes forever right after a redeploy), or the black spinner? I'd be a little more concerned with the spinner getting stuck, but if it eventually shows up, that might be enough to push to next for now.

**Comment by kkellerlbl** [comment]
Bill, unfortunately I haven't kept careful notes, so I can't say for sure how often each scenario comes up.  I've variously seen:

==the 502 bad gateway
==the 3-bubble gif which changes to the "Sorry, can't start a narrative" gif
==the black spinner getting stuck

I suspect (with no hard evidence) some of these issues may be related to the final DELETE request not going through the loopback interface on ci-narrative, and so not cleaning up old provisioned containers; till I can resolve that, I have been doing the delete by hand, but haven't always remembered to do it.  I'd like to see what happens on -next, in particular what happens if a user has a running container (this would also verify the "new version available" button), so before I do a deploy one of us should start a narrative and one of us should make sure we don't have one running.

If we can get people testing -ci today maybe we can go through the -next deploy together tomorrow.  (I can also do it tonight if you prefer more time to test on -next.)

**Comment by kkellerlbl** [comment]
I had some minor issues in -ci, but they're probably not appropriate for this discussion.  I can make a new issue in Github, in JIRA, or send email.  Bill what's your preference?

**Comment by r2sunita** [comment]
Sri and I tried to test expression matrix uploader at narrative-ci by uploading expression matrix file. 
Currently no Plant Genomes are available at narrative-ci.

We can't "Select the Genome object that contains features referenced by the Expression Matrix"

Got Error:
Import for [KBaseFeatureValues.ExpressionMatrix] type is not supported yet.

Sunita
________________________________________

**Comment by rsutormin** [comment]
@r2sunita Yes, because it's not merged into develop branch yet. Here is the discussion about what we should do before we can start to merge it.

**Comment by briehl** [comment]
The main things I'm concerned about failing on narrative-ci right now are, basically, loading up Narratives and seeing that they appear. The main changes that have been done on this branch affect that.

I'll go ahead and merge to next, then merge this in because it seems to be blocking work, and isn't dangerous. And from conversations at the meeting today, we really need to get charging on the expression data.

@kkellerlbl - when's the next deploy on next.kbase? Monday? Like you offered, can we step through that tomorrow?

**Comment by kkellerlbl** [comment]
I can deploy narrative-next whenever is best for you.  If you want to be present when I do it, let's do it tomorrow.  If you don't have a preference I can do it any time after the PR to staging is merged.

**Comment by briehl** [comment]
Ok. I'll open a PR to staging.

**Comment by kkellerlbl** [comment]
OK, thanks.  Did you want to wait till tomorrow to do the actual deploy on -next, or should I do it as soon as it's merged?

**Comment by kkellerlbl** [comment]
Okay, I've just merged the PR from develop to staging.  It should be safe to merge this PR now.  Once that's done we can wait till ci automatically redeploys or someone can force a rebuild from jenkins.  (I may kick off a manual build, since I want to see if I can replicate the issues I described above.)

**Comment by briehl** [comment]
If you're comfortable doing the build on -next now, I'm okay with that. Otherwise, we can do it tomorrow.
Merging this so it can get expression uploading in -ci.

**Comment by kkellerlbl** [comment]
Let's see how the -ci deploy goes.  I just started one from Jenkins.

**Comment by r2sunita** [comment]
Just now I  tried to test Expression matrix uploader on narrative-ci but getting problem to access full "Import" page. Tested it multiple times, after refreshing it but it happens every time. 

Please see the attached screenshot. 

Thanks.

Sunita


________________________________________

**Comment by kkellerlbl** [comment]
Sunita, there was no attachment.  Are you using email or Github directly?  If you're using email, Github may discard attachments, so try using Github from a browser instead.

**Comment by kkellerlbl** [comment]
I can see what you are referring to though: the "Import" tab is completely empty when I go to Data->Import.

**Comment by kkellerlbl** [comment]
Hmpf, now I can see the content in the Import pane.  Ugh!

**Comment by kkellerlbl** [comment]
The behavior is not consistent, unfortunately.  Bill and I will try to chase it down.  I have made some notes in the narrative channel on Slack.

**Comment by rsutormin** [comment]
So yeah, it looks like this PR is not yet deployed on CI.

**Comment by kkellerlbl** [comment]
It is definitely deployed.  From the git log on the deploy host:

> commit 0b98a24951195b7860c1b6f09d4a9cbceea507cd
> Merge: 95aa2e6 3c304e8
> Author: Bill Riehl <briehl@users.noreply.github.com>
> Date:   Thu Jul 23 13:36:29 2015 -0700
> 
>    Merge pull request #332 from rsutormin/dev-feature_values_upload
>
>    Expression matrix uploader is added into Narrative UI

The Import pane content not appearing properly seems to be a different issue.

**Comment by rsutormin** [comment]
Sorry, guys. I forgot to shutdown my IPython kernel. After that expression uploader works fine.

**Comment by rsutormin** [comment]
@r2sunita Sunita, have tried to restart Narrative IPython kernel?

**Comment by r2sunita** [comment]
Sorry, I sent an attachment through email therefore you might not have received it. I just relog in to narrative and tried again. Import pane is appearing fine now but when I tried to test Expression matrix uploader, I am getting an error. 

Here is console output: 

https://ci.kbase.us/services/search/getResults?itemsPerPage=20&page=1&q=*&category=genomes Failed to load resource: the server responded with a status of 502 (Bad Gateway)
ws.841.obj.1:1 XMLHttpRequest cannot load https://ci.kbase.us/services/search/getResults?itemsPerPage=20&page=1&q=*&category=genomes. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://narrative-ci.kbase.us' is therefore not allowed access. The response had HTTP status code 502.
static/dist/kbase-narrative-min.95f58031.js:24 Pausing for 500 ms before passing credentials to kernel
static/dist/kbase-narrative-min.95f58031.js:26 UJS file state saved: 34c36e85-3786-424f-9b39-72d5be089ce5 1437689318001
static/dist/kbase-narrative-min.95f58031.js:29 Data to be sent to transform service:
static/dist/kbase-narrative-min.95f58031.js:29 {"external_type":"TSV.Expression","kbase_type":"KBaseFeatureValues.ExpressionMatrix","workspace_name":"sunita:1437689289799","object_name":"ptr_ex_matrix_test","optional_arguments":{"validate":{},"transform":{"format_type":"Simple","fill_missing_values":1,"data_type":"log-ratio"}},"url_mapping":{"TSV.Expression":"https://ci.kbase.us/services/shock-api/node/34c36e85-3786-424f-9b39-72d5be089ce5"}}
static/dist/kbase-narrative-min.95f58031.js:29 Array[2]
static/dist/kbase-narrative-min.95f58031.js:29 Array[7]
static/dist/kbase-narrative-min.95f58031.js:29 Array[7]
static/dist/kbase-narrative-min.95f58031.js:29 Array[7]
static/dist/kbase-narrative-min.95f58031.js:29 Array[7]
static/dist/kbase-narrative-min.95f58031.js:29 loading detailed error...
static/dist/kbase-narrative-min.95f58031.js:29 Traceback (most recent call last):
  File "/kb/deployment/pybin/trns_upload_taskrunner.py", line 410, in upload_taskrunner
    task_output = handler_utils.run_task(logger, transformation_args, debug=debug)
  File "/kb/deployment/lib/biokbase/Transform/handler_utils.py", line 81, in run_task
    out = h.run(arguments, debug)
  File "/kb/deployment/lib/biokbase/Transform/handler_utils.py", line 155, in run
    raise Exception(task_output)
Exception: {'stderr': None, 'stdout': ''}

**Comment by rsutormin** [comment]
@r2sunita Sunita, can I ask you to send to Mike and me (to email box) your file with expression data which you're trying to upload?

**Comment by r2sunita** [comment]
Sure Roman. I will send it through email to both of you. Thanks.

**Comment by r2sunita** [comment]
I just tested Expression Matrix Uploader and could upload Poplar root expression matrix successfully :)

Thanks so much. 

Sunita

**Pull request merged**
