### PR TITLE
Another pass at styling

### PR DESCRIPTION
**Pull request by briehl**
* Removed padding between widgets and cell boundaries.
* Put method subtitle back where it belongs.
* Got rid of automatic black borders around tables.
* Added a left-side border for selected method/output cells.

### CODE REVIEW

**Comment by msneddon** [comment]
I just tried this out locally to check out the new styling updates (it keeps looking better!), and noticed that running on sdk methods gives me an error in kbaseNarrativeMethodCell.js, line 887, where it is trying to call hide() on $staticMethodInfo that is no longer defined.

**Comment by briehl** [comment]
D'oh! Thanks for checking.

**Comment by briehl** [comment]
I guess that brings up another thing - running tries to minimize the input area, but there's no way to restore it now, since the only minimize/maximize control is on the whole cell. This might become an issue.

**Comment by briehl** [comment]
Thanks for the help @msneddon . Merging this now.

**Pull request merged**
