### PR TITLE
GenomeClassifier Viewers

### PR DESCRIPTION
**Pull request by JamesJeffryes**
Adds simple viewers for GenomeCategorizer and GenomeClassifierTrainingSet

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@briehl I haven't added in tests yet. I'm going to try to replicate your test for the default viewer but may have to pester you a bit

**Comment by briehl** [comment]
Ok. Go ahead and pester if you need to. :)

**Comment by JamesJeffryes** [comment]
@briehl  OK, so I kind of cheated on the mocks. In one case, i'm pulling two different WS objects so I was not sure how to make that happen with `jasmine.Ajax.stubRequest`. My searching was not fruitful so I got lazy and inject the expected data to make sure the rendering code is functional. That's the section most prone to change so I think i've covered the most critical lines with these tests.

**Comment by briehl** [comment]
Looks fine to me.

**Pull request merged**
